### PR TITLE
add hopper in projects

### PR DESCRIPTION
**Pull request by spinpx**
Hi GJDuck,

We have used E9patch for instrumentation in [Hopper](https://github.com/FuzzAnything/hopper)'s implementation. Thank you for your great work in providing E9patch. Would you consider adding Hopper to the project list?

Thanks.

### CODE REVIEW

**Comment by GJDuck** [comment]
Thanks for the link, I am happy to add it to the README.

**Comment by GJDuck** [comment]
There is an `e9patch.diff` file that seems to be a fix for #56.  Can it be cleaned up and merged, or was there some problem with it?  I cannot recall.

**Comment by spinpx** [comment]
> There is an `e9patch.diff` file that seems to be a fix for #56. Can it be cleaned up and merged, or was there some problem with it? I cannot recall.

Thanks for your suggestion and I will check and clean the code.  I ignore it  since I always test the tool in Linux.

**Comment by AiDaiP** [comment]
Hi GJDuck,
Hopper needs to use custom initialization functions in Windows PE programs, so I made the code changes in #56 .
I did some testing on my Windows (19045.3570) using the latest version of e9patch and it worked.
This solution may not be general so I can't guarantee it will always be correct.

In addition, `e9patch.diff` in hopper has one more line of code changes than the one in #56 :
```
- else if (e9wcscasecmp(name->Buffer, L"user32.dll") == 0)
+ else if (e9wcscasecmp(name->Buffer, L"msvcrt.dll") == 0)
```
I changed this line because hopper need to call some functions in msvcrt.dll in `init()`. This is an inelegant but simple solution. It's not related to support Windows PE custom initialization functions.

**Pull request merged**
